"""ASR noise injection: a clean transcript in, a corrupted copy out.

The noise axis is the voice-native argument of the whole harness, so this module
has one job beyond corrupting text: being *exactly* reproducible. Every number
on the quality-vs-noise curve has to be re-derivable from
``(clean transcript, rate, noise_seed)`` and nothing else.

Why only user turns
-------------------
The interviewer's text is generated by the harness and is known exactly; there is
no recogniser between it and the transcript. ASR error lives on the user side, so
interviewer turns are passed through as the same objects (§3.10).

The seeding scheme, and why it is per turn
------------------------------------------
Each user turn draws from ``random.Random(f"{noise_seed}:{source_id}:{turn_id}")``,
keyed on the **clean** transcript's id. A single per-transcript RNG would consume
draws in turn order, so one extra follow-up turn — or a re-simulation that makes
turn three two words longer — would shift the stream and reshuffle the noise in
every later turn. The noised copy would then differ for reasons that have nothing
to do with the change, which is exactly the kind of silent movement this project
exists to prevent. Per-turn keying makes each turn's noise a pure function of the
seed, the clean transcript's id, the turn's id, and the rate.

"Seed" here means a Python-side ``random.Random`` and nothing else; the Messages
API has no seed parameter and none is ever sent (PLAN.md P3).

What ``edit_count`` counts
--------------------------
``edit_count`` is **the number of words at which an operation fired, including
punctuation strips that changed nothing**. The punctuation operation is
sentence-level but triggers per word and is idempotent, so counting changed
characters or changed sentences would make the rate-accounting test ill-defined.
Counting fire sites makes ``edit_count`` exactly ``Binomial(words, rate)``
(PLAN.md D4).

``rate == 0.0``
---------------
The ``Transcript`` validator forbids ``source_transcript_id`` when
``noise_rate == 0``, because a noise-free copy of a transcript is just the
transcript. So rate zero returns the clean transcript object itself — no new
artifact, no new id — with an edit log recording zero edits. Callers writing the
noise axis therefore write the clean transcript once at ``n000``.

The edit log
------------
§3.10 asks for a per-turn edit log, but ``Transcript`` forbids extra fields and
has nowhere to put one. The log is a sidecar artifact (``<stem>.edits.json``)
written beside the transcript: plain JSON, no model, nothing joined by position.
"""

from __future__ import annotations

import json
import random
from dataclasses import dataclass
from functools import cache
from pathlib import Path

from ..hashing import code_version
from ..models import ProvenanceStamp, Transcript, Turn, word_count
from ..paths import transcript_stem
from . import homophones

#: Drawn with ``rng.choice`` when the filler operation fires.
FILLERS: tuple[str, ...] = ("um", "uh", "like", "you know")

#: The four operations and their probabilities, conditional on an operation
#: firing at all (§3.10). Exactly one is applied per firing word.
OPERATION_WEIGHTS: tuple[tuple[str, float], ...] = (
    ("drop", 0.40),
    ("homophone", 0.30),
    ("filler", 0.20),
    ("punctuation", 0.10),
)

#: Stripped by the punctuation operation. Apostrophes and hyphens are left alone:
#: they are word-internal, and a recogniser that drops them produces a different
#: word, which is the homophone operation's job.
SENTENCE_PUNCTUATION = ".,;:!?"

#: A token ending in one of these closes the sentence it belongs to.
SENTENCE_TERMINATORS = ".!?"

EDIT_LOG_SUFFIX = ".edits.json"

#: Marks a shuffled-order transcript in its stem. ``Transcript`` has no
#: ``shuffled`` field, so the clean id is the only place the flag survives, and
#: the noised copy has to carry it through to avoid colliding with the
#: as-written run's artifact.
_SHUFFLED_MARKER = "__shuf__"


@dataclass(frozen=True)
class NoiseResult:
    """The noised transcript and its edit log, which are produced together."""

    transcript: Transcript
    edit_log: dict


def operation_for(draw: float) -> str:
    """Map a ``[0, 1)`` draw onto an operation using ``OPERATION_WEIGHTS``."""
    threshold = 0.0
    for name, weight in OPERATION_WEIGHTS:
        threshold += weight
        if draw < threshold:
            return name
    return OPERATION_WEIGHTS[-1][0]


def sentence_indices(tokens: list[str]) -> list[int]:
    """The sentence each token belongs to, so a strip can reach the whole sentence."""
    indices = []
    current = 0
    for token in tokens:
        indices.append(current)
        if token.rstrip("\"')]}").endswith(tuple(SENTENCE_TERMINATORS)):
            current += 1
    return indices


def strip_punctuation(token: str) -> str:
    """Drop sentence punctuation, unless that would erase the token entirely."""
    stripped = "".join(c for c in token if c not in SENTENCE_PUNCTUATION)
    return stripped or token


def _has_punctuation(tokens: list[str], sentences: list[int], sentence: int) -> bool:
    return any(
        any(c in SENTENCE_PUNCTUATION for c in token)
        for token, index in zip(tokens, sentences, strict=True)
        if index == sentence
    )


def noise_text(text: str, *, rate: float, rng: random.Random) -> tuple[str, list[dict]]:
    """Corrupt one user turn's text.

    Returns the new text and the turn's edit records. Words are the same words
    ``models.word_count`` counts, so the rate the test measures is the rate the
    metrics see.
    """
    tokens = text.split()
    sentences = sentence_indices(tokens)
    edits: list[dict] = []
    struck: set[int] = set()
    pieces: list[tuple[int, str]] = []

    for index, token in enumerate(tokens):
        sentence = sentences[index]
        if rng.random() >= rate:
            pieces.append((sentence, token))
            continue
        operation = operation_for(rng.random())
        record: dict = {"word_index": index, "word": token, "operation": operation}
        if operation == "drop":
            pass
        elif operation == "homophone":
            replaced = homophones.swap(token, rng)
            pieces.append((sentence, replaced.token))
            record["result"] = replaced.token
            record["source"] = replaced.source
        elif operation == "filler":
            filler = rng.choice(FILLERS)
            pieces.append((sentence, filler))
            pieces.append((sentence, token))
            record["filler"] = filler
        else:
            # Idempotent and sentence-level: a second strike on the same sentence,
            # or a sentence carrying no punctuation, changes nothing but is still
            # a fired operation (PLAN.md D4).
            record["sentence_index"] = sentence
            record["changed"] = sentence not in struck and _has_punctuation(
                tokens, sentences, sentence
            )
            struck.add(sentence)
            pieces.append((sentence, token))
        edits.append(record)

    noised = " ".join(
        strip_punctuation(token) if sentence in struck else token for sentence, token in pieces
    )
    return noised, edits


@cache
def _code_version() -> str:
    """``code_version()`` shells out to git; the answer is the same all run."""
    return code_version()


def _noised_stamp(source: Transcript, *, rate: float, seed: int) -> ProvenanceStamp:
    """Carry the clean transcript's stamp forward, with the noise parameters added.

    ``created_at`` is inherited rather than set to now: the noised copy is a pure
    function of its input, and an artifact whose bytes move on every call could
    not be compared for determinism.
    """
    return ProvenanceStamp(
        model=source.provenance.model,
        prompt_hash=source.provenance.prompt_hash,
        params={**source.provenance.params, "noise_rate": rate, "noise_seed": seed},
        code_version=_code_version(),
        created_at=source.provenance.created_at,
    )


def _noise_turn(turn: Turn, text: str) -> Turn:
    """Rebuild the turn through the validator, so ``word_count`` cannot drift.

    ``disclosed_fact_ids`` rides along unchanged: noise corrupts the rendering of
    what the person said, not what they said (§3.10).
    """
    return Turn.model_validate({**turn.model_dump(), "text": text, "word_count": word_count(text)})


def inject_noise(transcript: Transcript, *, rate: float, seed: int) -> NoiseResult:
    """Produce a noised copy of a clean transcript.

    The copy sets ``noise_rate``, ``noise_seed``, and ``source_transcript_id``;
    time-based metrics read word counts from that source, because dropped words
    and inserted fillers would otherwise move yield-per-minute for reasons
    unrelated to extraction (PLAN.md M8).
    """
    if not 0.0 <= rate <= 1.0:
        raise ValueError(f"noise rate must be in [0, 1], got {rate}")
    if transcript.noise_rate > 0:
        raise ValueError(
            f"transcript {transcript.transcript_id}: noise applies to clean transcripts only, "
            f"so that source_transcript_id names the noise-0 source (PLAN.md M8)"
        )
    if rate == 0.0:
        return NoiseResult(
            transcript,
            edit_log(transcript, {}, transcript_id=transcript.transcript_id, rate=0.0, seed=seed),
        )

    turns: list[Turn] = []
    edits_by_turn: dict[str, list[dict]] = {}
    for turn in transcript.turns:
        if turn.speaker != "user":
            turns.append(turn)
            continue
        rng = random.Random(f"{seed}:{transcript.transcript_id}:{turn.turn_id}")
        text, edits = noise_text(turn.text, rate=rate, rng=rng)
        turns.append(_noise_turn(turn, text))
        edits_by_turn[turn.turn_id] = edits

    noised = Transcript(
        transcript_id=transcript_stem(
            transcript.persona_id,
            transcript.sim_seed,
            rate,
            shuffled=_SHUFFLED_MARKER in transcript.transcript_id,
        ),
        persona_id=transcript.persona_id,
        script_hash=transcript.script_hash,
        sim_seed=transcript.sim_seed,
        noise_rate=rate,
        noise_seed=seed,
        source_transcript_id=transcript.transcript_id,
        turns=turns,
        simulated_minutes=round(sum(t.word_count for t in turns) / 150.0, 4),
        provenance=_noised_stamp(transcript, rate=rate, seed=seed),
    )
    return NoiseResult(
        noised,
        edit_log(
            transcript,
            edits_by_turn,
            transcript_id=noised.transcript_id,
            rate=rate,
            seed=seed,
        ),
    )


def edit_log(
    source: Transcript,
    edits_by_turn: dict[str, list[dict]],
    *,
    transcript_id: str,
    rate: float,
    seed: int,
) -> dict:
    """The sidecar log: what fired, where, and on which word.

    Built from the **clean** transcript and joined to turns by ``turn_id`` only.
    ``words`` is therefore the clean word count, which is the number of draws
    made, and ``edit_count`` is fire sites rather than changed characters
    (PLAN.md D4) — so ``edit_count`` over ``words`` is the rate the
    rate-accounting test checks.
    """
    turns = [
        {
            "turn_id": turn.turn_id,
            "words": turn.word_count,
            "edit_count": len(edits_by_turn.get(turn.turn_id, [])),
            "edits": edits_by_turn.get(turn.turn_id, []),
        }
        for turn in source.turns
        if turn.speaker == "user"
    ]
    return {
        "transcript_id": transcript_id,
        "source_transcript_id": source.transcript_id if rate > 0 else None,
        "noise_rate": rate,
        "noise_seed": seed,
        "user_words": sum(t["words"] for t in turns),
        "edit_count": sum(t["edit_count"] for t in turns),
        "turns": turns,
    }


def edit_log_path(directory: Path, transcript_id: str) -> Path:
    return Path(directory) / f"{transcript_id}{EDIT_LOG_SUFFIX}"


def write_edit_log(log: dict, directory: Path) -> Path:
    """Write the sidecar beside the transcript it describes."""
    path = edit_log_path(directory, log["transcript_id"])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(log, indent=2, sort_keys=True) + "\n")
    return path
